name: check_updates

on:
  workflow_dispatch:
  schedule:
    # do this once a week
    - cron: "0 7 * * 2"

jobs:
  build:
    name: check updates
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
      RUSTC_FORCE_INCREMENTAL: 1

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ROSLYN_REPO_PAT }}

      - uses: denoland/setup-deno@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ROSLYN_REPO_PAT }}
        run: |
          git config user.email "dsherret@users.noreply.github.com"
          git config user.name "dsherret"
          deno run -A ./scripts/update.ts
